version: "3.7"

services:


  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: theusername
      POSTGRES_PASSWORD: thepassword
      POSTGRES_DB: macronizer
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      
  flask:
    build: ./flask
    depends_on: 
      - db
    container_name: flask
    networks:
      - default
    restart: always
    environment:
      - APP_NAME=cltk_api_docker_ci
      - DATABASE_URL=postgresql://theusername:thepassword@db:5432/macronizer
    expose:
      - 8080
    
volumes:
  postgres_data:
