# This is a basic workflow to help you get started with Actions

name: cltk_api_docker_ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: connect to droplet; pull from repo; docker-compose
        timeout-minutes: 10 # Times out after 1 minute
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker image prune
            touch /tmp/uwsgi.log
            chown -R www-data:www-data /tmp/
            chmod -R 777 /tmp/uwsgi.log
            cd cltk_api_docker_ci/
            git init
            git config --global user.name "bblumenfelder"
            git config --global user.email "benedikt.blumenfelder@gmail.com"
            git pull https://github.com/bblumenfelder/cltk_api_docker_ci.git
            docker-compose up --build
            exit


